### ISSUE TITLE
-Wsequence-point raises warning about potential undefined behaviour

### ISSUE THREAD

**Issue by olimasters** [olimasters/magnet-automaton#8]
54:45 of Magnet.cpp.
This should either be refactored, or it should be scrutinised to make sure that it _is_ in fact defined behaviour.

**Comment by AlexSWall** [comment]
I don't know what -Wsequence-point is, but I've double-checked and it looks like, assuming i,j are valid indices of the array, behaviour will all be defined.

**Comment by olimasters** [comment]
-Wsequence-point is one of the flags given to gcc by the -Wall flag.  The issue is that behaviour is undefined in some cases when the same variable is changed by more than one operation with side effects in the same expression.  For example, I think that
```
int i = 0;
i = i++ + i++;
```
is undefined behaviour.  However, in this case, due to the presence of the `&&` operators, I think we are okay.  See https://en.wikipedia.org/wiki/Sequence_point for some more reading on the matter

**Comment by olimasters** [comment]
In fact, even `i = i++` is undefined behaviour.

**Comment by AlexSWall** [comment]
Riight... perhaps. I am not certain in any way.

**Comment by AlexSWall** [comment]
I am happy to learn the concept of a "sequence point" in Java is not a thing.

**Comment by olimasters** [comment]
This repository is a Java-free zone I'm afraid

**Comment by AlexSWall** [comment]
I believe we are guaranteed the increment to the variable 'neighbours' necessarily occurs before checking its boolean state, and no other assignment occurs (on the right hand side), so I don't think there is a problem.

**Comment by olimasters** [comment]
True.  I might end up changing it just out of being annoyed by the compiler warning though.

**Comment by AlexSWall** [comment]
Change it how? I assume you're not going to change it to the way I was thinking of doing it?
